import fs from "node:fs/promises";
import path from "node:path";
import { executeCommandTool } from "@/tools/terminal/commandUtils.js";

export class PulumiService {
    private workspaceDir: string;

    constructor(projectName: string = "nexusflow-deployment") {
        this.workspaceDir = path.resolve(process.cwd(), ".workspace", projectName);
    }

    /**
     * Materializes artifacts to disk.
     */
    public async prepareWorkspace(artifacts: Record<string, { body: string; type: string }>) {
        await fs.mkdir(this.workspaceDir, { recursive: true });

        // Ensure Pulumi configuration exists
        if (!artifacts["Pulumi.yaml"]) {
            await fs.writeFile(
                path.join(this.workspaceDir, "Pulumi.yaml"),
                `name: nexusflow-deployment\nruntime: python\ndescription: Auto-generated by NexusFlow`
            );
        }

        for (const [filename, artifact] of Object.entries(artifacts)) {
            await fs.writeFile(path.join(this.workspaceDir, filename), artifact.body, "utf-8");
        }
    }

    /**
     * Executes Pulumi commands via the secure tool registry.
     */
    private async runCommand(cmd: string): Promise<string> {
        // We use the tool's logic directly. 
        // This ensures the same security/HITL checks apply to Pulumi actions.
        const result = await executeCommandTool.invoke({
            command: `cd ${this.workspaceDir} && ${cmd}`
        });

        return result;
    }

    public async deploy(): Promise<{ success: boolean; logs: string }> {
        try {
            // 1. FORCE PULUMI INTO LOCAL MODE (Prevents the PULUMI_ACCESS_TOKEN error)
            console.log("🔐 Forcing Pulumi to use Local State Backend...");
            await this.runCommand("pulumi login --local");

            // 2. Initialize the stack
            console.log("🔄 Initializing Pulumi Stack...");
            await this.runCommand("pulumi stack init dev").catch(() => {
                // Ignore errors if stack already exists
            });

            // 3. Run the deployment
            console.log("🚀 Running Pulumi Up...");
            const output = await this.runCommand("pulumi up --yes --stack dev");

            // We check the tool output for common failure strings
            const isSuccess = !output.includes("error:") && !output.includes("failed");

            return {
                success: isSuccess,
                logs: output
            };
        } catch (error: any) {
            return {
                success: false,
                logs: error.message
            };
        }
    }
}