import { BaseMessage } from "@langchain/core/messages";
import { Annotation } from "@langchain/langgraph";

/**
 * The shared memory for the agentic workflow.
 */
export const AgentState = Annotation.Root({
    // Append new messages to the existing list
    messages: Annotation<BaseMessage[]>({
        reducer: (currentState, newMessages) => currentState.concat(newMessages),
        default: () => [],
    }),
    // The structured plan generated by the Cloud Architect
    cloudPlan: Annotation<any>({
        reducer: (curr, next) => next ?? curr,
        default: () => null,
    }),
    // The code artifacts generated by the Coders
    artifacts: Annotation<Record<string, { body: string; type: "python" | "json" | "yaml"; target: string }>>({
        reducer: (curr, next) => ({ ...curr, ...next }),
        default: () => ({}),
    }),
    // Captured logs from Validator or Pulumi deployment
    validationErrors: Annotation<string | null>({
        reducer: (curr, next) => next, // Overwrite with latest errors
        default: () => null,
    }),
    // Tracks if deployment was successful to end the graph
    deploymentStatus: Annotation<"PENDING" | "SUCCESS" | "FAILED">({
        reducer: (curr, next) => next ?? curr,
        default: () => "PENDING",
    }),
    // Current cloud context for routing decisions (e.g., AWS, Azure, Databricks)
    currentCloudContext: Annotation<"AWS" | "AZURE" | "DATABRICKS" | "CROSS_CLOUD">({
        reducer: (curr, next) => next ?? curr,
        default: () => "CROSS_CLOUD",
    }),
    // Retry count for handling transient errors and implementing backoff strategies
    retryCount: Annotation<number>({
        reducer: (curr, next) => curr + (next ?? 1),
        default: () => 0,
    }),
    // Metadata about the infrastructure being provisioned, useful for decision-making and logging
    infraMetadata: Annotation<Record<string, any>>({
        reducer: (curr, next) => ({ ...curr, ...next }),
        default: () => ({}),
    }),
});